### ISSUE TITLE
Unit Tests are Broken

### ISSUE THREAD

**Issue by NickGrantCEO** [ONSdigital/rm-party-service-api#14]
The package has been renamed, breaking the unit tests.

The unit tests are pretty useless - they just check that Lombok works - but surely these broken tests should be breaking the CI/CD pipeline?

**Comment by benjefferies** [comment]
Seems to be passing in travis and for me locally https://travis-ci.org/ONSdigital/rm-party-service-api. I guess you're right that they don't do much other than test lombok but I guess it will catch regression if the annotation is removed

**Comment by NickGrantCEO** [comment]
From the travis log:
`[INFO] [INFO] -------------------------------------------------------
[INFO] [INFO]  T E S T S
[INFO] [INFO] -------------------------------------------------------
[INFO] [INFO] Running uk.gov.ons.ctp.response.party.definition.SampleLinkCreationRequestDTOTest`

The package name of the tests is uk.gov.ons.ctp.response.party.definition

The package name of the classes is uk.gov.ons.ctp.response.party.representation

I have no idea how the unit tests could be working - they're in a different package and there's no import statement for the under test classes.

**Comment by NickGrantCEO** [comment]
Ah... the classes are generated from the XSD... yes works for me when I do local Maven build
